### ISSUE TITLE
Components missing

### ISSUE THREAD

**Issue by donovantc** [nik-john/react-redux-multi-stage-form-wizard#1]
Hi Nikhil,

I tried to run your app but there are at least 2 errors which are causing the app to fail:

1.  `./app/containers/Form/index.js` is trying to resolve `./components/StartSectionComponent` but it does not exist

2. `./app/containers/Form/components/Result.js` is trying to resolve `components/ShadowContainer` but it also does not exist.

Perhaps you forgot to commit some of your latest changes?

Cheers,
Donovan

**Comment by nik-john** [comment]
Hi Donovan, that sounds weird.

I don't seem to be able to reproduce this issue. I tried to clone afresh and set up the app.

I followed the following steps: 

1. `git clone git@github.com:nik-john/react-redux-multi-stage-form-wizard.git app && cd app`
2. `yarn && yarn start`
3. `yarn run test:watch` (2 tests are still failing here, but that's because I've not had the time to fix them

I am running Node 8, but any >5 version will do. Also, I'm using a Mac. What OS are you using?

I have pushed some tests that seemed to be breaking. Could you try pulling the latest please?

**Comment by nik-john** [comment]
@donovantc Any luck with this?

**Comment by donovantc** [comment]
@nik-john I see that [this commit](https://github.com/nik-john/react-redux-multi-stage-form-wizard/commit/2d79ee937b6997c761a27c2e936ec0cee44bac82) now added the 2 missing components which I mentioned. So now it's running, thanks 👍

**Comment by nik-john** [comment]
👍
